### PR TITLE
Fix AWS credentials problem

### PR DESCRIPTION
**Pull request by zdehasek**

### CODE REVIEW

**Comment by kodermax** [comment]
Thanks for this PR!

**Comment by zdehasek** [comment]
@kodermax can I know why you reverted my commits? It is anything bad with my changes ?
Thanks in advance :)

**Comment by kodermax** [comment]
yes in this issue https://github.com/kodermax/kubectl-aws-eks/issues/11 the user got an error.

**Comment by zdehasek** [comment]
Thx for the info. And sorry for the trouble, I will fix it and send PR again.

**Comment by zdehasek** [comment]
@kodermax one more questing, are you using this actions for AWS EKS ? And are you able to execute kubernetes commands without credentials in ~/.aws/credentials ?

**Pull request merged**
